name: miniscriptgenlib
description: A code generator annotations for Miniscript.
version: 0.0.1-alpha14
repository: https://github.com/dartleaf/miniscript.genlib

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  miniscript: ^1.6.2-11
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
